#本地默认配置情况
server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到Eureka Server，默认为true
    fetch-registry: false #是否从Eureka Server获取注册信息，默认为true
    service-url:
      defaultZone: http://localhost:8761/eureka/ #设置与Eureka Server交互的地址