#本地默认配置情况
server:
  port: 8762
  
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true #是否从Eureka Server获取注册信息，默认为true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  ignored-services: '*'
#  sensitive-headers: Cookie,Set-Cookie,Authorization
  sensitive-headers: Cookie,Set-Cookie
  retryable: true
  routes:
    baidu:
      path: /baidu/**
      url: https://www.baidu.com
#    auth:
#      #权限认证服务
#      path: /api/**
#      service-id: api
#      strip-prefix: true
#    report:
#      #报表分析服务
#      path: /report/**
#      service-id: report
#      strip-prefix: true
#    admin:
#      #前端与后台调用
#      path: /**
#      service-id: admin
#      strip-prefix: true